---
- hosts: tentacode.net
  vars_files:
    - credentials.yml

  tasks:
    - name: Cloning git repository
      git:
        repo: https://{{ github_user|urlencode }}:{{ github_password|urlencode }}@github.com/tentacode/tentacode.net.git
        dest: /srv/www/tentacode.net

    - name: Composer install
      command: composer install
      args:
        chdir: /srv/www/tentacode.net

    - name: Npm install
      command: npm install
      args:
        chdir: /srv/www/tentacode.net
      become: yes
      become_method: sudo

    - name: Grunt install
      command: ./node_modules/.bin/grunt
      args:
        chdir: /srv/www/tentacode.net