---
- hosts: tentacode.net
  become: yes
  become_method: sudo
  
  roles:
    - bash
    - git
    - php-fpm
    - nginx
    - node
    - permission
    - role: symfony
      project_name: tentacode.net
      server_names: tentacode.net www.tentacode.net
